config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :facilities
  get 'pages/home'

  get 'pages/facilities'

  get 'pages/restaurant'

  get 'pages/conference'

  get 'pages/booking'

  get 'pages/contact_us'

  resources :rooms
  root "rooms#index"

end

app/models/facility.rb
class Facility < ActiveRecord::Base
end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "hoanggiahotel"
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:title, :description, :shot_title)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @rooms = Room.all
  end

  def facilities
    @rooms = Room.all
    @facilities = Facility.all
  end

  def restaurant
    @rooms = Room.all
    @facilities = Facility.all
  end

  def conference
    @rooms = Room.all
  end

  def booking
    @rooms = Room.all
  end

  def contact_us
    @rooms = Room.all
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:title, :description)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @newspapers = Newspaper.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/common/_booking.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>hotel-fortune bootstrap Design website | Home :: w3layouts</title>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>
<link href="css/bootstrap.css" rel='stylesheet' type='text/css'/>
<link href="css/style.css" rel="stylesheet" type="text/css" media="all"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="js/jquery.min.js"></script>
</head>
<body>
<div class="contact-bg2">
	 <div class="container">
		 <div class="booking">
			 <h3>Booking</h3>
			 <div class="col-md-8 booking-form">			 
				 <form>
				 <h5>NAME</h5>
				 <input type="text" value="">
				 <h5>E-MAIL</h5>
				 <input type="text" value="">
				 <h5>PHONE</h5>
				 <input type="text" value="">
				 <h5>TIME</h5>
				 <input type="text" value="" class="time">
				 <h5>CHECK IN</h5>
				 <select class="arrival">
					 <option>01</option>
					 <option>02</option>
					 <option>03</option>
					 <option>04</option>
					 <option>05</option>
					 <option>06</option>
					 <option>08</option>
					 <option>09</option>
					 <option>10</option>
					 <option>11</option>
					 <option>12</option>
					 <option>13</option>
					 <option>14</option>
					 <option>15</option>
					 <option>16</option>
					 <option>17</option>
					 <option>18</option>
					 <option>19</option>
					 <option>20</option>
					 <option>21</option>
					 <option>22</option>
					 <option>23</option>
					 <option>24</option>
					 <option>25</option>
					 <option>26</option>
					 <option>27</option>
					 <option>28</option>
					 <option>29</option>
					 <option>30</option>
					 <option>31</option>					 
				 </select>
				 <select class="arrival">
					 <option>Jan</option>
					 <option>Feb</option>
					 <option>Mar</option>
					 <option>Apr</option>
					 <option>May</option>
					 <option>June</option>
					 <option>July</option>
					 <option>Aug</option>
					 <option>Sep</option>
					 <option>Oct</option>
					 <option>Nov</option>					 
					 <option>Dec</option>
				 </select>
				 <select class="arrival">
					<option>2012</option>
					<option>2013</option>
					<option>2014</option>
					<option>2015</option>
					<option>2016</option>
					<option>2017</option>
				 </select>
				 <h5>CHECK OUT</h5>
				 <select class="arrival">
					 <option>01</option>
					 <option>02</option>
					 <option>03</option>
					 <option>04</option>
					 <option>05</option>
					 <option>06</option>
					 <option>08</option>
					 <option>09</option>
					 <option>10</option>
					 <option>11</option>
					 <option>12</option>
					 <option>13</option>
					 <option>14</option>
					 <option>15</option>
					 <option>16</option>
					 <option>17</option>
					 <option>18</option>
					 <option>19</option>
					 <option>20</option>
					 <option>21</option>
					 <option>22</option>
					 <option>23</option>
					 <option>24</option>
					 <option>25</option>
					 <option>26</option>
					 <option>27</option>
					 <option>28</option>
					 <option>29</option>
					 <option>30</option>
					 <option>31</option>					 
				 </select>
				 <select class="arrival">
					 <option>Jan</option>
					 <option>Feb</option>
					 <option>Mar</option>
					 <option>Apr</option>
					 <option>May</option>
					 <option>June</option>
					 <option>July</option>
					 <option>Aug</option>
					 <option>Sep</option>
					 <option>Oct</option>
					 <option>Nov</option>					 
					 <option>Dec</option>
				 </select>
				 <select class="arrival">
					<option>2012</option>
					<option>2013</option>
					<option>2014</option>
					<option>2015</option>
					<option>2016</option>
					<option>2017</option>
				 </select>
				 <h5 class="mem">MEMBERS</h5>
				 <input min="1" type="number" id="quantity" name="quantity" value="1" class="form-control input-small">
				 <h5>REQUIRED</h5>
				 <textarea value=""></textarea>
				 <input type="submit" value="Submit">
				 <input type="reset" value="Reset">
				 </form>			      
			 </div>
			 <div class="col-md-4 booking-news">
				 <h4>Latest News</h4>			
				 <div class="LatestNews">
					 <h6><a href="#">Starting New Ventures for a Current Bussi</a></h6>
					 <span>01-7-2014 </span>
					 <p>Faworki bonbon marshmallow caramels applicake tart gummi bears liquorice.</p> 
				 </div>			
				 <div class="LatestNews">
					 <h6><a href="#">Starting New Ventures for a Current Bussi</a></h6>
					 <span>01-7-2014 </span>
					 <p>Faworki bonbon marshmallow caramels applicake tart gummi bears liquorice.</p> 
				 </div>	
					<div class="LatestNews">
					 <h6><a href="#">Starting New Ventures for a Current Bussi</a></h6>
					 <span>01-7-2014 </span>
					 <p>Faworki bonbon marshmallow caramels applicake tart gummi bears liquorice.</p> 
				 </div>	
				 <div class="LatestNews">
					 <h6><a href="#">Starting New Ventures for a Current Bussi</a></h6>
					 <span>01-7-2014 </span>
					 <p>Faworki bonbon marshmallow caramels applicake tart gummi bears liquorice.</p> 
				 </div>	
			 </div>
		
				<div class="clearfix"> </div>

			 </div>
		 </div>
	 </div>
</div>
</body>
</html>

app/views/common/_conference.html.erb
<div class="confer">
	<script src="js/responsiveslides.min.js"></script>
	 <script>
    // You can also use "$(window).load(function() {"
    $(function () {
      $("#conference-slider").responsiveSlides({
      	auto: true,
        manualControls: '#slider3-pager',
      });
    });
  </script>
  <div class="container">
    <h2>Hoàng Gia Hotel <span>CONFERENCE</span></h2>
    <div class="conference-slider">
	    <!-- Slideshow 3 -->
	    <ul class="conference-rslide" id="conference-slider">
	      <li><img src=<%=image_path("c1.jpg")%> alt=""></li>	 
	    </ul>
    </div> 
	<h4>Conference Halls in Hoàng Gia Hotels</h4>
     <p>A big announcement, a new idea or a special occasion demands a venue to match. A name your guest will be delighted to see on the invitation - a place to impress, inspire and linger in the memory. It's a tall order. Allow us to make things a little easier for you with our collection of luxury London hotels.</p>
	 <p>Each Deluxe Hotels in World has its own unique personality. So you can give your event that unique atmosphere and feel. Between them all, Deluxe Hotels the  offer a huge range of room sizes and layouts that can be configured to your precise requirements. Whether you're arranging a board meeting or banquet, product launch or wedding, you've come to the right place.</p>
	 <p>The Charing Cross Hotel, has 9 meeting rooms, the largest of which can accommodate up to 150 people.</p>
	 <p>The Deluxe Hotel, near Marble Arch in London has 26 meeting rooms, the largest of which can accommodate up to 400 people. The Deluxe Hotel adjoining One Whitehall Place have 13 meeting rooms, the largest of which can accommodate up to 340 people.The Tower Hotel, near Tower Bridge in London has 19 meeting rooms, the largest of which can accommodate up to 600 people.</p>
	 <div class="sponcers">
		<div class="sponcers-head">
		<h5>Featured Sponsors</h5>
		</div>
	 </div>
	<script type="text/javascript">
	 $(window).load(function() {
		$("#flexiselDemo1").flexisel({
			visibleItems: 3,
			animationSpeed: 1000,
			autoPlay: true,
			autoPlaySpeed: 3000,    		
			pauseOnHover: true,
			enableResponsiveBreakpoints: true,
			responsiveBreakpoints: { 
				portrait: { 
					changePoint:480,
					visibleItems: 1
				}, 
				landscape: { 
					changePoint:640,
					visibleItems: 2
				},
				tablet: { 
					changePoint:768,
					visibleItems: 3
				}
			}
		});
		
	});
   </script>
   <script type="text/javascript" src="js/jquery.flexisel.js"></script>		
	 </div>
 </div>
 
 </div>

app/views/common/_contact.html.erb
<div class="contact-bg">
	 <div class="container">
	      <div class="contact-us">				
				<div class="contact-us_left">
					<div class="contact-us_info">
			    	 	<h3 class="style">Find Us Here</h3>
			    	 		<div class="map">

			    	 			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.058517869089!2d106.62464349999998!3d10.806830200000007!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752be381b835b3%3A0x8bc350ff01e8b46e!2zMTk0IEzDqiBUcuG7jW5nIFThuqVuLCBUw6JuIFBow7osIEjhu5MgQ2jDrSBNaW5oLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1435025894933" width="100%" height="175" frameborder="0" style="border:0" allowfullscreen></iframe>
					   		</div>
      				</div>
      			 <div class="company_address">
				     	<h3 class="style">Hotel Information :</h3>
						<p>500 Lorem Ipsum Dolor Sit,</p>
						<p>22-56-2-9 Sit Amet, Lorem,</p>
						<p>USA</p>
				   		<p>Phone:(00) 222 666 444</p>
				   		<p>Fax: (000) 000 00 00 0</p>
				 	 	<p>Email: <a href="mailto:info@example.com">info(at)myhotel.com</a></p>
				   		<p>Follow on: <a href="#">Facebook</a>, <a href="#">Twitter</a></p>
				   </div>
				</div>				
				<div class="contact_right">
				  <div class="contact-form">
				  	<h3 class="style">Contact Us</h3>
					    <form method="post" action="index.html">
					    	<div>
						    	<span><label>NAME</label></span>
						    	<span><input name="userName" type="text" class="textbox"></span>
						    </div>
						    <div>
						    	<span><label>E-MAIL</label></span>
						    	<span><input name="userEmail" type="text" class="textbox"></span>
						    </div>
						    <div>
						     	<span><label>MOBILE</label></span>
						    	<span><input name="userPhone" type="text" class="textbox"></span>
						    </div>
						    <div>
						    	<span><label>SUBJECT</label></span>
						    	<span><textarea name="userMsg"> </textarea></span>
						    </div>
						   <div>
						   		<input type="submit" value="submit us">
						  </div>
					    </form>
				    </div>
  				</div>		
  				<div class="clear"></div>		
		  </div>
	 </div>	
</div>

app/views/common/_facilities.html.erb
<div class="main_bg">
	 <div class="container">
		 <div class="main">	          
			   <ul class="service_list">
			   	<% @facilities.each do |facility|%>
				 	<li>
					   	<div class="ser_img">
						    <a href="details.html">
							<img src=<%=image_path("ser_pic1.jpg")%> alt="" />
							<span class="next"> </span>
							</a>
				        </div>	
						<a href="details.html"><h3><%= facility.title %></h3></a>
						<p class="para">There are many variations of passages of Lorem Ipsum available,</p>
						<h4><a  href="details.html"><%= facility.shot_title %></a></h4>
					</li>
				<% end %>
			  </ul>
		   </div>
	  </div>
</div>

app/views/common/_restaurant.html.erb
<div class="rooms text-center">
	 <div class="container">
		 <h3>Our Restaurants</h3>
		 <div class="room-grids">
		 	<% @restaurants.each do |restaurant|%>
			 <div class="col-md-4 room-sec">
				 <a href="#"><img src=<%=image_path("pic1.jpg")%> alt=""/></a>
				 <div class="caption">
					<span>&#8356; 250</span>
					<a href="contact.html">Book Now</a>
				 </div>
				 <h4><%= restaurant.title %></h4>
				 <p><%= restaurant.description %></p>
			 </div>
			 <% end %>
			 <div class="clearfix"></div>
		 </div>
	 </div>
</div>

app/views/common/_roomtype.html.erb
<div class="rooms text-center">
	<div class="container">
		<h3>Our Room Types</h3>
		<div class="room-grids">
			<% @rooms.each do |room| %>
				<div class="col-md-4 room-sec">
					<img src=<%=image_path("pic1.jpg")%> alt="<%= room.title %>"/>
					<h4><%= room.title %></h4>
					<p><%= room.description %></p>
					<div class="items">
						<li><a href="#"><span class="img1"> </span></a></li>
						<li><a href="#"><span class="img2"> </span></a></li>
						<li><a href="#"><span class="img3"> </span></a></li>
						<li><a href="#"><span class="img4"> </span></a></li>
						<li><a href="#"><span class="img5"> </span></a></li>
						<li><a href="#"><span class="img6"> </span></a></li>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :shot_title %><br>
    <%= f.text_field :shot_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Facilities</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Shot title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility.title %></td>
        <td><%= facility.description %></td>
        <td><%= facility.shot_title %></td>
        <td><%= link_to 'Show', facility %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility', new_facility_path %>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @facility.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @facility.description %>
</p>

<p>
  <strong>Shot title:</strong>
  <%= @facility.shot_title %>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/layouts/_bookingroom.html.erb
<div class="b_room">
		<div class="booking_room">
			<div class="reservation">
				<ul>				
					<li  class="span1_of_1 left">
						<h5>Arrival</h5>
						<div class="book_date">
							<form>
								<input class="date" id="datepicker" type="text" value="2/08/2013" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '2/08/2013';}">
							</form>
						</div>					
					</li>
					<li  class="span1_of_1 left">
						<h5>Depature</h5>
						<div class="book_date">
							<form>
								<input class="date" id="datepicker1" type="text" value="22/08/2013" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '22/08/2013';}">
							</form>
						</div>		
					</li>
					<li class="span1_of_1">
						<h5>Room type</h5>
						<div class="section_room">
							<select id="country" onchange="change_country(this.value)" class="frm-field required">
								<% @rooms.each do |room| %>
									<option value="null"><%= room.title %></option>
								<% end %>
							</select>
						</div>	
					</li>
					<li class="span1_of_3">
						<div class="date_btn">
							<form>
								<input type="submit" value="View Prices" />
							</form>
						</div>
					</li>
					<div class="clearfix"></div>
				</ul>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>

app/views/layouts/_header.html.erb
<div class="top-header">
	<div class="container">
		<div class="logo">
			<a href="index.html"><img src=<%=image_path("logo.png") %>/></a>
		</div>
		<span class="menu"> </span>
		<div class="m-clear"></div>
		<div class="top-menu">
			<ul>
				<li class="active"><%= link_to "HOME", pages_home_path %></li>
				<li><%= link_to "FACILITIES", pages_facilities_path %></li>
				<li><%= link_to "RESTAURANT", pages_restaurant_path %></li>
				<li><%= link_to "CONFERENCE", pages_conference_path %></li>
				<li><%= link_to "BOOKING", pages_booking_path %></li>
				<li><%= link_to "CONTACT US", pages_contact_us_path %></li>
			</ul>
			<script>
				$("span.menu").click(function(){
					$(".top-menu ul").slideToggle(200);
					});
				</script>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<div class="banner">
	<div class="banner-info text-center">
		<h3><label>Hello,</label> You've Reached</h3>
		<h1>HOANG GIA HOTEL</h1>
		<span></span>
		<ul>
			<li><a class="scroll" href="#">HOTEL</a><i class="line"></i></li>
			<li><a class="scroll" href="#">SPA SALOON</a><i class="line2"></i></li>
			<li><a class="scroll" href="#">FINE DINING</a></li>
			<div class="clearfix"></div>
		</ul>
	</div>
</div>

app/views/pages/booking.html.erb
<%= render "common/booking"%>

app/views/pages/conference.html.erb
<%= render "common/conference"%>

app/views/pages/contact_us.html.erb
<%= render "common/contact"%>

app/views/pages/facilities.html.erb
<%= render "common/facilities" %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.title %></td>
        <td><%= restaurant.description %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @restaurant.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>